### ISSUE TITLE
ENG_patch

### ISSUE THREAD

**Issue by birdydma** [parshukov/An24-Felis-for-XP11#1]
Good day Николай

First of all: thank you.

i have converted few png in dds. Seem good for me.
For some reason, they are very light against the russian stock dds.

PS: you should remove the ENG_patch as it will confused a lot of pilots.
[ENG_patch.zip](https://github.com/parshukov/An24-Felis-for-XP11/files/1520939/ENG_patch.zip)

**Comment by parshukov** [comment]
replaced
