### ISSUE TITLE
Smartco

### ISSUE THREAD

**Issue by birdydma** [parshukov/An24-Felis-for-XP11#3]
Here is a better file.

Can you add 2 custom commands to deactivate the AP with a joystick button? (pilot and copilot)

As it is with the custom datarefs, the synchronization does not work. 

PS: BetterPushback is sync with this file.
[smartcopilot.zip](https://github.com/parshukov/An24-Felis-for-XP11/files/1520966/smartcopilot.zip)

**Comment by parshukov** [comment]
replaced
