### ISSUE TITLE
smartcopilot.cfg

### ISSUE THREAD

**Issue by birdydma** [parshukov/An24-Felis-for-XP11#4]
Some FO's lights are not sync with the previous file.

Here is the new one
[smartcopilot.zip](https://github.com/parshukov/An24-Felis-for-XP11/files/1540531/smartcopilot.zip)

**Comment by parshukov** [comment]
Btw, I found in smartco file strings:
parshukovedition/lights/CCFDLAMP[0] = 0
parshukovedition/lights/CCFDLAMP[1] = 0
parshukovedition/lights/CCFDLAMP[2] = 0
parshukovedition/lights/CCFDLAMP[3] = 0
parshukovedition/lights/CCFDLAMP[4] = 0
parshukovedition/lights/CCFDLAMP[5] = 0
parshukovedition/lights/CCFDLAMP[6] = 0
parshukovedition/lights/CCFDLAMP[7] = 0
parshukovedition/lights/CCFDLAMP[8] = 0
And this lines also for all my custom lights! I want to ask you to check that only parshukovedition/lights/CFDLAMP[3] with INDEX 3 must be sync! Cause it is brightness. Other values are for creating light and they needn't be sync. 
 so the strings should be:
```
parshukovedition/lights/CCFDLAMP[3] = 0
parshukovedition/lights/CFDLAMP[3] = 0
parshukovedition/lights/overhead_lamp_left[3] = 0
parshukovedition/lights/overhead_lamp_pilotright[3] = 0
parshukovedition/lights/LFDGaugesDownLeft[3] = 0
parshukovedition/lights/RFDGaugesDownLeft[3] = 0
parshukovedition/lights/LFDLAMP[3] = 0
parshukovedition/lights/RFDLAMP[3] = 0
```

**Comment by birdydma** [comment]
Tested and approved. Good job.

PS: overhead is very dark at night. I can see here only with the flash light.

**Comment by parshukov** [comment]
Thx. It was done for XP10 already) So can you send me the  latest smartcopilot cfg?
About overhead - what if you try to set on main light in the cockpit? there two switches on the overhead near the cockpit door. 
Can you send me a screen?

**Comment by birdydma** [comment]
[smartcopilot.zip](https://github.com/parshukov/An24-Felis-for-XP11/files/1542828/smartcopilot.zip)

Here is the new file

**Comment by birdydma** [comment]
![2017-12-08_15h07_00](https://user-images.githubusercontent.com/30256581/33769207-92054e4e-dc29-11e7-8f55-a40d50f3e8c5.jpg)

Pic of the overhead, lights on with the 2 switches.

Also, could you ad custom commands to disconnect AP with buttons. Should be better to sync this fonction with smartco, and even flying alone with a joystick button.

**Comment by parshukov** [comment]
done. you can try. But also it is necessery to recreate some lights and improve then. Really I do not know if I do it..

About command to turn off AP - use "sim/autopilot/fdir_servos_down_one"
