### ISSUE TITLE
Spotlights

### ISSUE THREAD

**Issue by birdydma** [parshukov/An24-Felis-for-XP11#5]
It's very difficult to catch the lateral arrows tu turn the spots.

PS: overhead lights are now nice.

**Comment by parshukov** [comment]
do you mean click zones?

**Comment by birdydma** [comment]
2 Pics. Obvious in one case, impossible in the other one.

![easy](https://user-images.githubusercontent.com/30256581/33856733-5805c1f4-dec9-11e7-9d43-04f386c40518.jpg)

![impossible](https://user-images.githubusercontent.com/30256581/33856747-61934c46-dec9-11e7-9449-f1e0e376d223.jpg)

**Comment by parshukov** [comment]
[An24_v11_cockpit.zip](https://github.com/parshukov/An24-Felis-for-XP11/files/1552223/An24_v11_cockpit.zip)
Can you try spots with this file?

**Comment by birdydma** [comment]
Your are fantastic.

**Comment by parshukov** [comment]
so, it is done?

**Comment by birdydma** [comment]
Yes indeed!
