### ISSUE TITLE
Clocks and smartco

### ISSUE THREAD

**Issue by birdydma** [parshukov/An24-Felis-for-XP11#7]
![2017-12-12_19h48_42](https://user-images.githubusercontent.com/30256581/33902698-26fdb1c2-df76-11e7-9acc-d11d4b5fe128.jpg)

In the An24, we have 2 of those clocks (we use them to do holds flying online).

I can't catch similar datarefs in the An24 to sync them. Are they hidden somewhere?

**Comment by parshukov** [comment]
I think you should find some kind of commands for this clocks. I found in Felis file achs1:
sim/instruments/timer_start_stop
sim/instruments/timer_reset

**Comment by birdydma** [comment]
Yes, i know, they are in the .cfg without any effect.
In the TU154M, for 3 clocks:

## AChS-1
sim/custom/gauges/acs1/left_knob_press = 0
sim/custom/gauges/acs1/right_knob_press = 0
sim/custom/gauges/acs2/left_knob_press = 0
sim/custom/gauges/acs2/right_knob_press = 0
sim/custom/gauges/acs3/left_knob_press = 0
sim/custom/gauges/acs3/right_knob_press = 0

**Comment by parshukov** [comment]
[test achs.zip](https://github.com/parshukov/An24-Felis-for-XP11/files/1553499/test.achs.zip)

Try this one and for clock and smartcopilot use:
parshukovedition/clocks/sec_mode = 0
parshukovedition/clocks/flight_mode = 0

**Comment by birdydma** [comment]
Good day,

Wow, you are fast, sometimes i sleep.

Right and left clocks are tied. 

No click spots over the buttons

Master and slave does not displays the same elapsed time

**Comment by parshukov** [comment]
Ok! I can hear click spots...can you recheck it?
As for master and slave wait for 10 min

**Comment by parshukov** [comment]
ok! Try this one with smart
[test achs.zip](https://github.com/parshukov/An24-Felis-for-XP11/files/1554815/test.achs.zip)

and add this datarefs:
parshukovedition/clocks/sec_mode = 0
parshukovedition/clocks/flight_mode = 0
parshukovedition/clocks/chrono_sec_angle = 0
parshukovedition/clocks/chrono_min_angle = 0
parshukovedition/clocks/flight_min_angle = 0
parshukovedition/clocks/flight_hour_angle = 0

**Comment by birdydma** [comment]
I can hear click spots.

Chrono sec_and min angle starts at 0 for the pilot pushing the knob, and about 3.5 and 233 for the other one. 
Of course needles are flickering.

Flight timer: Same, start with different times, but needles does not move.

WIP.

**Comment by parshukov** [comment]
Ok! try this one
[test achs.zip](https://github.com/parshukov/An24-Felis-for-XP11/files/1555311/test.achs.zip)

**Comment by birdydma** [comment]
Better. Now all values are sync.

Flight timer: needles does not move.

Chrono: perfect if the master launch it. If the slave does, there is a reminder, and the chrono starts to its last position.

**Comment by parshukov** [comment]
what kind of reminder?

**Comment by parshukov** [comment]
try this one for Flight Timer
[achs1.zip](https://github.com/parshukov/An24-Felis-for-XP11/files/1555481/achs1.zip)

**Comment by birdydma** [comment]
If the slave launch the chrono for the first time, it start from 0. Then stop after 10 sec or so. One more click = 0 OK.
Starting  again by the slave, it will start from 10 sec, not 0.

Works as intended when the master does the manip

**Comment by parshukov** [comment]
[achs1.zip](https://github.com/parshukov/An24-Felis-for-XP11/files/1555560/achs1.zip)
and now?

**Comment by birdydma** [comment]
Flight timer: needles are moving.

Same problem with flight timer and chrono for the slave side.

I have only dowloaded again the plane, not the whole sim.

**Comment by parshukov** [comment]
[test achs.zip](https://github.com/parshukov/An24-Felis-for-XP11/files/1555594/test.achs.zip)

and now?
btw - do not forget to copy new avionics.lua

**Comment by parshukov** [comment]
and also put this datarefs in the "CONTINUE" section of the config
parshukovedition/clocks/sec_mode = 0
parshukovedition/clocks/flight_mode = 0
parshukovedition/clocks/chrono_sec_angle = 0
parshukovedition/clocks/chrono_min_angle = 0
parshukovedition/clocks/flight_min_angle = 0
parshukovedition/clocks/flight_hour_angle = 0

**Comment by birdydma** [comment]
Sorry, i will continue in few hours.

**Comment by parshukov** [comment]
ok

**Comment by birdydma** [comment]
Same result, very strange.

**Comment by parshukov** [comment]
It needs to write another code for clocks that will work for standalone and for smartcopilot...

**Comment by birdydma** [comment]
Ok, no hurry, we can live as it is, unless you are a perfectionist.

You already did a very nice job.

**Comment by parshukov** [comment]
[test achs.zip](https://github.com/parshukov/An24-Felis-for-XP11/files/1556537/test.achs.zip)
and what about now ;)

**Comment by birdydma** [comment]
Gooooooooooood.

I join the .cfg. Tests done with the 2.08 release of the plugin (i forgot to mention this one. I was testing this new release since few days).
[smartcopilot.zip](https://github.com/parshukov/An24-Felis-for-XP11/files/1558288/smartcopilot.zip)

**Comment by parshukov** [comment]
nice)) I am a bit of a perfectionist, so did not want to leave it undone)))
I close this issue and will publish a new release with spot lights, clocks, smartcopilot cfg and some improvements with ark system.

**Comment by birdydma** [comment]
Did a quick test, not on my Lan, but thru internet with my usual copilot of the An24, and the TU154.

Lights, overhead and clocks. Perfect, but,

Hey, you have launch my chrono!
No, there are now tied.
What, i am jealous, i have not my own chronometer as i have the Tu!

Anyway, topic closed.

**Comment by parshukov** [comment]
heh! ok! I understood :) 
btw, when you fly without smartcopilot and start left watch, the right watch also begin to run? If so, it need to make this clock in 3D. Now it is rendered via SASL...

**Comment by birdydma** [comment]
Clocks are separate (and not sync) since XP9, tied (and sync) with your new files, flying alone or not.

**Comment by parshukov** [comment]
very strange, cause in files I can see only achs1.lua for both clocks...I will look at it. Also I will look at the laretest Felis version for xp10

**Comment by birdydma** [comment]
My bad. I have memory leaks.

Just tested with XP10, your are right.
