### ISSUE TITLE
SmartCopilot double fuel consumption 

### ISSUE THREAD

**Issue by parshukov** [parshukov/An24-Felis-for-XP11#8]
When flying with smartcopilot there is double fuel consumption. Need to check it!

**Comment by birdydma** [comment]
Will test asap, probably tomorrow.

**Comment by birdydma** [comment]
Few datarefs added in the continued section. Some = 1 , it is not a typo.

All values are similar, no difference of fuel used with or without smartco.

Can you confirm?

![2017-12-14_16h29_07](https://user-images.githubusercontent.com/30256581/34003308-41e5f294-e0f5-11e7-9072-99ba7b9f7a54.jpg)


![2017-12-14_16h37_34](https://user-images.githubusercontent.com/30256581/34003321-476dbc38-e0f5-11e7-81a9-d78b29b311de.jpg)


![2017-12-14_16h45_47](https://user-images.githubusercontent.com/30256581/34003327-4c4ddbb6-e0f5-11e7-8cbb-25c9177be020.jpg)

[smartcopilot.zip](https://github.com/parshukov/An24-Felis-for-XP11/files/1560036/smartcopilot.zip)

**Comment by parshukov** [comment]
ok, I will check it.

**Comment by parshukov** [comment]
ok! and what about indicators in the cockpit? 
Fuel QTY Indicator, flow meter?

**Comment by birdydma** [comment]
Same values, same position.

Ideally, both sim should display at 30 fps, or above, 25 min.

Install DiscreetFPS (  https://forums.x-plane.org/index.php?/files/file/19392-discreetfps-display-the-current-framerate-discreetly/&tab=comments#comment-118857 ).

If one sim is too slow, the synchronization of some values can be hazardous. For exemple, 60 sec in real world can be displayed after 75 sec in the 3D pit. As time is sync via the continued section, problems may occur.

**Comment by parshukov** [comment]
I think it is ok. Close issue
